\name: Daily Server Status Check

# Scheduled daily at 6:41 PM US Eastern
on:
  schedule:
    - cron: '41 22 * * *'  # 6:41 PM EDT (UTC 22:41)
    - cron: '41 23 * * *'  # 6:41 PM EST (UTC 23:41)
  workflow_dispatch:  # allows manual runs

jobs:
  check_status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Show workflow runtime
        run: |
          echo "UTC time: $(date -u)"
          echo "Eastern time: $(TZ=America/New_York date)"

      - name: Run monitor script
        run: python monitor.py
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
