name: Daily Server Status Check

# Scheduled daily at 6:50 PM US Eastern
on:
  schedule:
    - cron: '50 22 * * *'  # 6:50 PM EDT (UTC 22:50)
    - cron: '50 23 * * *'  # 6:50 PM EST (UTC 23:50)
  workflow_dispatch:  # Allows manual runs anytime

jobs:
  check_status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug environment
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          echo "DISCORD_WEBHOOK_URL is set? ${DISCORD_WEBHOOK_URL:+Yes}"
          echo "Current UTC time: $(date -u)"
          echo "Current Eastern time: $(TZ=America/New_York date)"

      - name: Run monitor.py
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          python monitor.py
